channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=24.2
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==6.0.0
  - scikit-learn==1.5.1
  - scipy==1.13.1
name: mlflow-env
